### ISSUE TITLE
Add MongoDB

### ISSUE THREAD

**Issue by RenanLazarotto** [JeroenBoersma/docker-compose-development#109]
Its pretty straightforward - add a MongoDB container. Since your stack is meant for development, MongoDB would be a nice addition.

[The MongoDB Docker Hub page](https://hub.docker.com/_/mongo) has a docker-compose sampĺe:

```yaml
# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
```
It worked for me by using their sample config, but I might be missing something (and it also should be available to everybody else =) )

Thanks and keep up with your amazing work!
