### ISSUE TITLE
Add Postgresql

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#131]
We need Postgresql for Ergonode :(

**Comment by peterjaap** [comment]
I added this to my `docker-compose.yml`;

```
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

```

Then `dev rebuild`

Got the IP from the container; `docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps | grep postgres | cut -d ' ' -f1)`

Installed postgres locally; `sudo apt install postgres postgres-contrib`

And logged in like this; `psql -U postgres -h 172.18.0.2`
