### ISSUE TITLE
Running Laravel Dusk

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#135]
Laravel Dusk relies on Selenium and headless Chrome.

Following the [official installation guide](https://laravel.com/docs/8.x/dusk#installation) until you reach the point where you start `php artisan dusk` - it will fail with an error it can't reach localhost:9515.

Now add the following to your `docker-custom.yml` file (or create it in your development dir if it doesn't exist);

```
version: '3'

services:

    php74:
        links:
            - selenium

    selenium:
        image: selenium/standalone-chrome
        container_name: dusk-selenium
        network_mode: bridge
```

Run `dev up` and `docker ps` and you should see your new container;

```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
d0f1f36ec6fa        selenium/standalone-chrome   "/opt/bin/entry_poin…"   4 minutes ago       Up 4 minutes        0.0.0.0:4444->4444/tcp                                                                       dusk-selenium
......etc
```

Edit your `DuskTestCase.php` and replace `driver()` with;

```
    protected function driver()
    {
        $options = (new ChromeOptions)->addArguments([
            '--disable-gpu',
            '--headless',
            '--window-size=1920,1080',
            '--no-sandbox',
            '--verbose'
        ]);

        $seleniumHost = 'http://localhost:9515';
        if (count(app()->getProviders('Laravel\Dusk\DuskServiceProvider'))) {
            $seleniumHost = 'http://selenium:4444/wd/hub';
        }

        return RemoteWebDriver::create(
            $seleniumHost, DesiredCapabilities::chrome()->setCapability(
                ChromeOptions::CAPABILITY, $options
            )
        );
    }
```

Now run `php artisan dusk` and it should run.
