### ISSUE TITLE
Curl doesn't work

### ISSUE THREAD

**Issue by esjdev** [JeroenBoersma/docker-compose-development#136]
I'm using **DNSMASQ**.

When I try to use curl, this error.

I already mechi in **/etc/hosts**, **/etc/resolv.conf**. And I couldn't solve it :(

`#Could not resolve host: web.project.localhost`

**Comment by peterjaap** [comment]
Find the IP of your `web` container; `docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps | grep web |  cut -d ' ' -f1)`

Let's assume it's `172.17.0.1` and you're trying to connect to `web.project.localhost` from the `php73` container.

Now create a `docker-custom.yml` in your `development` dir and place this;

```
version: '3'

services:
    php73:
        extra_hosts:
            - web.project.localhost:172.17.0.1
```
