### ISSUE TITLE
installing magento 2

### ISSUE THREAD

**Issue by tgigli-trezo** [JeroenBoersma/docker-compose-development#142]
Hi there,

I have an issue that I am not sure how to fix it.
I get the console using `dev console` and then I'm trying to run `bin/magento setup:di:compile` and it runs out of memory and shows me:
`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /data/xxx/magento2/setup/src/Magento/Setup/Module/Di/Compiler/ArgumentsResolver.php on line 216`

The php is configured with 512M
```
app@4c192f8793e7:~/asus/magento2$ php -i |grep -i memory_limit
memory_limit => 512M => 512M
```

How can I change the php-cli memory_limit?

**Comment by JeroenBoersma** [comment]
I console, you can always run `php -d 'memory_limit=-1' bin/magento set:di:com`

You can create these files:

`build/custom/php/php.ini `
```
sendmail_path = "/usr/bin/msmtp --host=mailcatch --port=1025 -f app@fpm.dev -t "

upload_max_filesize = 64M
memory_limit = -1
log_errors = 1
error_reporting = E_ALL

xdebug.mode = develop,debug
xdebug.client_host = 172.17.0.1

xdebug.max_nesting_level = 1024
```

`build/custom/php/Dockerfile`
```
ARG FROM_IMAGE=srcoder/development-php
ARG FROM_TAG=php71-fpm

FROM ${FROM_IMAGE}:${FROM_TAG}
LABEL maintainer="Jeroen Boersma <jeroen@srcode.nl>"

ARG GID=1000
ARG UID=1000

RUN groupmod -g $GID app && \
    usermod -g $GID -u $UID app

COPY php.ini /usr/local/etc/php/php.ini
```

and update/create a `docker-custom.yml` in the root.

```
version: '3'                   
                                                     
services:                              

  php72:
    build:
      context: build/custom/php

  php73:
    build:
      context: build/custom/php

  php74:
    build:
      context: build/custom/php
```

After that run 
```
# build the images again with new settings
dev build

# drop en recreate containers
dev down && dev up

```

Hope this helps you out
