### ISSUE TITLE
MySQL 8 support

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#143]
We need it for Akeneo 4 and 5. Magento 2 can now run on MySQL 8 too.

**Comment by peterjaap** [comment]
`build/custom/docker-compose-mysql8.yml`

```
volumes:
  dockerdev-mysql8-volume:
    external: true

services:
  mysql8:
    image: mysql:8
    container_name: dockerdev-mysql8
    volumes:
      - ./conf.d/mysql/my.cnf:/etc/my.cnf.d/development.cnf:ro
      - dockerdev-mysql8-volume:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 127.0.0.1:3307:3307
```

`touch conf/mysql8`
