### ISSUE TITLE
Add Valkey 8

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#190]
Next to Redis. Valkey is the new preferred key-value storage engine.

**Comment by JeroenBoersma** [comment]
Yes it is! Someone screwed licensing 🍿 - It could be as simple as `docker-custom.yml`

```yaml
services:
# ...
  redis:
    image: docker.io/valkey/valkey
# ...
```
