### ISSUE TITLE
Adminer: web db management

### ISSUE THREAD

**Issue by Caroga** [JeroenBoersma/docker-compose-development#46]
As I was explaining how to use entities in symfony to a friend of mine, I thought: I could really use some sort of GUI to manage my database contents.

Then I thought, maybe it's a good addition to add Adminer to the set?
https://github.com/clue/docker-adminer

Would love to hear your opinion on this.

**Comment by JeroenBoersma** [comment]
I think I wont include it directly as port 3306 is already mapped to your localhost, so you could easily use any GUI you want(For instance your favorite Jetbrains product)

Of coarse if you would, you could.

Add in your `docker-custom.yml` (untested, think it will almost work)

```yaml

services:
  adminer:
    image: clue:adminer
    links:
      - db:db
    ports:
      - 81:80

```

Open localhost:81 and us db as host, everything else as you prefer.

Of coarse feel free to provide some feedback
