### ISSUE TITLE
Add Varnish

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#65]
For now, I'm using [fballiano/varnish](https://github.com/fballiano/docker-varnish). I've added it in my `docker-custom.yml`;

```
version: '2'

services:
    varnish:
        image: fballiano/varnish
        ports:
          - "81:80"
          - "6082:6082"
        depends_on:
          - web
        network_mode: bridge
        links:
          - web
        volumes:
          - ./workspace/path/to/your.vcl:/etc/varnish/default.vcl
          - ./varnish.secret:/etc/varnish/secret
        environment:
          - CACHE_SIZE=256M
```

This binds your host port 81 to the web's 80. So change the base URL to include port 81 for Varnish.

For the secret, I'm using the secret from Fabrizio's repo (https://github.com/fballiano/docker-magento2/blob/master/varnish.secret) but I'm not sure whether that is necessary.

For Magento 2, just run `dev down && dev up` after adding this and you're good to go.

For Magento 1, you'll also need libvmod-headers. SSH into the Varnish container and run; 

```
apt-get update && apt-get install -y varnish-dev zip build-essential automake libtool python-docutils
cd ~
curl -LO https://github.com/varnish/varnish-modules/archive/master.zip
unzip master.zip
cd varnish-modules-master
./bootstrap
./configure
make
make install
```

For some VCL settings, we also use libvmod-querystring. Install that too;

```
cd ~
curl -OL https://github.com/Dridi/libvmod-querystring/releases/download/v1.0.3/vmod-querystring-1.0.3.tar.gz
tar xvf vmod-querystring-1.0.3.tar.gz
cd vmod-querystring-1.0.3
./configure --with-rst2man=:
make
make install
```

We should build our own varnish image with this pre-installed.
