### ISSUE TITLE
Cannot get xdebug to work

### ISSUE THREAD

**Issue by pquerner** [JeroenBoersma/docker-compose-development#71]
The docs on how to use Xdebug are not enough for me it seems. Could you show more on how to use it perhaps? Ie. how to setup the IDE (pref. PHPStorm) to debug the simple "test" project (which is bundled) ?

**Comment by pquerner** [comment]
I have created a docker-custom.yml file with this content:

```
version: '2'
services:
    php:
      environment:
        SSH_AUTH_SOCK: "/ssh-socket"
        XDEBUG_CONFIG: "remote_host=192.168.1.158 idekey=PHPSTORM"
```

Now xdebug wont connect to 172.17.0.1 but to my local IP address.

I guess your workflow (with the other static ip) would work too, but I cannot get it to work sadly.
