### ISSUE TITLE
Use switcher for Xdebug/Blackfire

### ISSUE THREAD

**Issue by elzekool** [JeroenBoersma/docker-compose-development#9]
Hi,

With the addition of Blackfire you loose the ability to use Xdebug. I have a suggestion to allow you to use both. It depends on the fact that Xdebug is triggered by a cookie 'XDEBUG_SESSION'. There are extentions for Firefox (https://addons.mozilla.org/en-US/firefox/addon/the-easiest-xdebug/) and Chrome (https://chrome.google.com/webstore/detail/eadndfjplgieldjbigjakmdgkmoaaaoc) to set this cookie.

My version of the development environment diverted to much to easily create a PR, so I'll try to explain it in this issue:

Update the Dockerfile of phpfpm to include xdebug and blackfire, but create an ini file in a seperate directory:

``` Dockerfile
# Install XDEBUG
RUN pecl install xdebug \    
    && mkdir -p $PHP_INI_DIR/conf.xdebug.d/ \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > $PHP_INI_DIR/conf.xdebug.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> $PHP_INI_DIR/conf.xdebug.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> $PHP_INI_DIR/conf.xdebug.d/xdebug.ini \
    && echo "xdebug.remote_connect_back=on" >> $PHP_INI_DIR/conf.xdebug.d/xdebug.ini \
    && echo "xdebug.remote_port=9000" >> $PHP_INI_DIR/conf.xdebug.d/xdebug.ini

# Install blackfire agent
RUN export VERSION=`php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;"` \
    && mkdir -p $PHP_INI_DIR/conf.blackfire.d/ \  
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/${VERSION} \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp \
    && mv /tmp/blackfire-*.so `php -r "echo ini_get('extension_dir');"`/blackfire.so \
    && echo "extension=blackfire.so\nblackfire.agent_socket=\${BLACKFIRE_PORT}" > $PHP_INI_DIR/conf.blackfire.d/blackfire.ini
```

Update the Docker compose file to create two PHPFPM instances, but each with a changed PHP_INI_SCAN_DIR, excluding the blackfire link from the xdebug enabled container and add a new link to the nginx container.

``` yml
# ...
phpfpm:
    # ...
    environment:
        - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d/:/usr/local/etc/php/conf.blackfire.d/
    # ...
    links:
        - db
        - mailcatcher
        - blackfire

phpfpmx:
    # ...
    environment:
        - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d/:/usr/local/etc/php/conf.xdebug.d/
    # ...
    links:
        - db
        - mailcatcher

# ...

web:
    # ...
    links:
        - phpfpm:fpm
        - phpfpmx:fpmx
        # ...
```

Change the nginx/nginx/nginx.conf file to include two upstream configurations, one for fpm and one for fpmx

``` nginx
# ...
http {
    # ...
    upstream fpm {
        server fpm:9000;
    }

    upstream fpmx {
        server fpmx:9000;
    }
    # ...
}
```

Create a new file in the nginx/nginx folder, the name doesn't really matter, i've choosen phpfpm.conf. 

``` nginx
if ($http_cookie ~ "XDEBUG_SESSION") {
    fastcgi_pass   fpmx;
}

if ($http_cookie !~ "XDEBUG_SESSION") {
    fastcgi_pass   fpm;
}
```

In the different server configurations (in your case nginx/nginx/sites-available/vhost/*.content) remove the reference to fastcgi_pass and add an include to phpfpm.conf (or whatever you named this file)

``` nginx
location ~ \.php(/|$) {
   #...
   # fastcgi_pass fpm;
   include phpfpm.conf;
   #...
}
```

The only downside of the above switch is that it will loose any PHP session as those are stored in each container. For this reason I added a new volume to the phpfpm container

``` yml
#...
phpfpm:
    #...   
    volumes:
        - ./phpsessions:/tmp/phpsessions/
    #...

#...
phpfpmx:
    #...
    volumes_from:
        # Instead of data
        - phpfpm
    #...
```

And then configuring PHP to use this new volume for sessions by adding a new line to phpfpm/etc/php.ini

``` ini
session.save_path = /tmp/phpsessions
```
