### ISSUE TITLE
Can't increase memory_limit

### ISSUE THREAD

**Issue by RenanLazarotto** [JeroenBoersma/docker-compose-development#94]
Hello there!

I've tried to follow the custom PHP version doc to create a version on which I have a bigger `memory_limit` value (I'm currently looking for 2G). I've created `build/custom/phpmg` and placed the `Dockerfile` inside it. Then I've created the `conf` directory, with `php.ini` and `php-fpm.conf` on it. On `php.ini`, I've definded my desired `memory_limit` value. Then I copied the `web` folder (from `build/dist`) to `build/custom`, changed the `backends.conf` and `content/php` to add the `phpmg` checks.

Then I've added `docker-custom.yml` to the main folder (in my case, /home/renan/docker) with the following content:
```
version: '3'
services:
  phpmg:
    build: build/custom/phpmg
    links:
      - db
      - mailcatch
      - redis
    network_mode: bridge
  web:
    build: build/custom/web
    links:
      - phpmg:fpmmg
```
It builds OK, but when I try using `.phpmg` to define which version I want, my `memory_limit` is still set to 512M! Running dev changephp or dev php-change doesn't show my custom PHP. What I've missed?

**Comment by peterjaap** [comment]
@JeroenBoersma ?

**Comment by RenanLazarotto** [comment]
So I decided to give another try. I did the same steps, but changed a line or two here and there. This time, I've did the very same steps, but used `php6` as my desired version. So, here's what I've did:
- from `JeroenBoersma/docker-php` repository, I've copied the `php72/fpm` directory to `build/custom/php6`
- in `build/custom/web/backends.conf`, I added the following lines:
```
upstream fastcgi6_backend {
    server fpm6:9000;
}
```
 - `on build/custom/web/content/php`, I added the following lines:
```
if ( -f $dev_base_root/.php6 ) {
  set $php '6';
}
if ( -f $dev_customer_root/.php6 ) {
  set $php '6';
}
if ( -f $dev_root/.php6 ) {
  set $php '6';
}
```
 - rebuilt everything, no issues at all
 - just to try, I ran `dev changephp {randomstuff}` just to see if my 'version' was shown. It wasn't.

Also, I've noticed one thing: there is a file called `php` inside `bin` directory. This directly conflicts with the locally installed php, since it is added to `PATH`. Is this by design? I ask because I only need to increase the `memory_limit` parameter to install Magento 2 Sample Data (because this is the ONLY time where composer ran out of memory). I wanted to try with my local PHP installation, but it ran from the container version, **which I cannot increase the memory_limit**.

So, my suggestions:
- I don't know much about how docker works, but maybe you can add a support for mapping php.ini somewhere local (if this is feasible);
- Again, since my docker knowledge is limited, I don't know if this is possible, but add support for .user.ini inside the project root;
- If any of these two are already possible, please add a how-to in the docs. This can be quite useful;
- Check if the bin/php behaviour is the desired one. I've just renamed the file, but this might be an issue?

**Comment by RenanLazarotto** [comment]
Oh, I forgot to mention, my `docker-custom.yml` looks like this now:
```
version: '3'
services:
  php6:
    build: build/custom/php6
    links:
      - db
      - mailcatch
      - redis
    network_mode: bridge
  web:
    build: build/custom/web
    links:
      - php6:fpm6
```

**Comment by JeroenBoersma** [comment]
Hi @RenanLazarotto, thanks for asking...
Will try to fulfill all questions...

> Also, I've noticed one thing: there is a file called php inside bin directory. This directly conflicts with the locally installed php, since it is added to PATH. Is this by design? I ask because I only need to increase the memory_limit parameter to install Magento 2 Sample Data (because this is the ONLY time where composer ran out of memory). I wanted to try with my local PHP installation, but it ran from the container version, which I cannot increase the memory_limit.

Yes, because in our world we don't use locally installed PHP anymore.
Everything should be dockerized..

You buy new hardware, install docker and docker-compose, add dev to your PATH.
And your are all set, have a fully working PHP environment inside docker and still the possibility to use `php` which also translates to the correct `php` version for a given project.

**Comment by JeroenBoersma** [comment]
So, on memory limit, I've changed a few bits and bytes to make it easier to maintain and I think I forgot to update the `docs` (sorry for that)

So, right now we have one file to set some final bits and pieces for PHP, like user and permissions.
The correct file for this is https://github.com/JeroenBoersma/docker-compose-development/blob/master/build/dist/php/Dockerfile

Easiest: copy `dist/php` to `custom/php`
Copy your `conf` with `php.ini` and(if needed) `php-fpm.conf`

Add a line to the `Dockerfile`
```
# Copy config files
COPY conf/php-fpm.conf /usr/local/etc/
COPY conf/php.ini /usr/local/etc/php/
```

Update your settings reflecting `memory_limit`
Examples in: https://github.com/JeroenBoersma/docker-php/blob/master/php72/fpm/Dockerfile

After that, open `docker-custom.yml` and for the php version where you want to have this new setting:

```yml
version: '3'

services:
  php71:
    build:
      context: build/dist/php
  php72:
    build:
      context: build/dist/php
```

`dev build` will rebuild the images needed with the updated section.
`dev down && dev up` will destroy and recreate the environment.

Hope this explains what needs to be done. I'll leave this open as a reminder to update the docs :)

**Comment by JeroenBoersma** [comment]
If you really want the new PHP version, which isn't derived from a current build, than indeed create a php6 directory, add all the file like you did in https://github.com/JeroenBoersma/docker-compose-development/issues/94#issuecomment-497076723

To make use of that version from the commandline with `dev php-change`
```yaml
version: '3'
services:
  php60:
    build: build/custom/php6
    links:
      - db
      - mailcatch
      - redis
    network_mode: bridge
  web:
    build: build/custom/web
    links:
      - php60:fpm6
```

The annotation is majorminor, so php60 instead of php6
